// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425100327_InitialSQLite")]
    partial class InitialSQLite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7286),
                            PasswordHash = "$2a$11$VAKioSvVwsy0rU8u/H1myOra9fVL4.G/hXo1/CGEvGgKAnT0Iz8/O",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7288),
                            PasswordHash = "$2a$11$K9fA3fewFqSVSNRRLgOmK.Gx0M99u9zrr1yNMtYyvgqDgekU4r8RO",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7771),
                            Department = "Engineering",
                            Email = "pooja.ghosh@XYZ.com",
                            FirstName = "Pooja",
                            JoinDate = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ghosh",
                            Phone = "9876543210",
                            Role = "DevOps Engineer",
                            Salary = 750000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7772)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7786),
                            Department = "Operations",
                            Email = "amit.joshi@XYZ.com",
                            FirstName = "Amit",
                            JoinDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Joshi",
                            Phone = "9876543211",
                            Role = "Supply Chain Analyst",
                            Salary = 600000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7786)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7793),
                            Department = "Marketing",
                            Email = "lakshmi.chandran@XYZ.com",
                            FirstName = "Lakshmi",
                            JoinDate = new DateTime(2021, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chandran",
                            Phone = "9876543212",
                            Role = "Brand Manager",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7793)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7799),
                            Department = "Finance",
                            Email = "suresh.babu@XYZ.com",
                            FirstName = "Suresh",
                            JoinDate = new DateTime(2022, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Babu",
                            Phone = "9876543213",
                            Role = "Tax Consultant",
                            Salary = 700000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7799)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7806),
                            Department = "Engineering",
                            Email = "meera.krishnan@XYZ.com",
                            FirstName = "Meera",
                            JoinDate = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Krishnan",
                            Phone = "9876543214",
                            Role = "QA Engineer",
                            Salary = 650000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7806)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7813),
                            Department = "HR",
                            Email = "rahul.sharma@XYZ.com",
                            FirstName = "Rahul",
                            JoinDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sharma",
                            Phone = "9876543215",
                            Role = "HR Executive",
                            Salary = 500000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7814)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7831),
                            Department = "Engineering",
                            Email = "vikram.singh@XYZ.com",
                            FirstName = "Vikram",
                            JoinDate = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Singh",
                            Phone = "9876543216",
                            Role = "Software Engineer",
                            Salary = 900000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7832)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7838),
                            Department = "Finance",
                            Email = "neha.gupta@XYZ.com",
                            FirstName = "Neha",
                            JoinDate = new DateTime(2022, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gupta",
                            Phone = "9876543217",
                            Role = "Financial Analyst",
                            Salary = 720000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7838)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7845),
                            Department = "Marketing",
                            Email = "anjali.desai@XYZ.com",
                            FirstName = "Anjali",
                            JoinDate = new DateTime(2023, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Desai",
                            Phone = "9876543218",
                            Role = "SEO Specialist",
                            Salary = 550000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7845)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7878),
                            Department = "Operations",
                            Email = "karan.patel@XYZ.com",
                            FirstName = "Karan",
                            JoinDate = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Patel",
                            Phone = "9876543219",
                            Role = "Operations Manager",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7878)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7886),
                            Department = "HR",
                            Email = "riya.sen@XYZ.com",
                            FirstName = "Riya",
                            JoinDate = new DateTime(2021, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sen",
                            Phone = "9876543220",
                            Role = "Talent Acquisition",
                            Salary = 680000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7886)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7892),
                            Department = "Engineering",
                            Email = "rohit.verma@XYZ.com",
                            FirstName = "Rohit",
                            JoinDate = new DateTime(2019, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Verma",
                            Phone = "9876543221",
                            Role = "Tech Lead",
                            Salary = 1200000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7892)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7899),
                            Department = "Marketing",
                            Email = "sneha.reddy@XYZ.com",
                            FirstName = "Sneha",
                            JoinDate = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reddy",
                            Phone = "9876543222",
                            Role = "Content Strategist",
                            Salary = 600000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7899)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7905),
                            Department = "Finance",
                            Email = "arjun.nair@XYZ.com",
                            FirstName = "Arjun",
                            JoinDate = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nair",
                            Phone = "9876543223",
                            Role = "Accountant",
                            Salary = 500000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7905)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7925),
                            Department = "Operations",
                            Email = "priya.menon@XYZ.com",
                            FirstName = "Priya",
                            JoinDate = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Menon",
                            Phone = "9876543224",
                            Role = "Logistics Coordinator",
                            Salary = 450000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 25, 10, 3, 27, 338, DateTimeKind.Utc).AddTicks(7926)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
